/*
 * This source file was generated by the Gradle 'init' task
 */
package sisop_trab_1;

public class App {

    public static void main(String[] args) {
       Escalonador escalonador = new Escalonador();
       escalonador.execucaoEscalonar(); 
    }
}